### ISSUE TITLE
black potion of luck lowering stat

### ISSUE THREAD

**Issue by aniserg** [Tomsod/elemental#2]
Potion of luck +76 lowered luck by 8 somehow (used on lvl 1 character)

elemental 3.1.1
grayface 2.5.7

before potion:
![before](https://github.com/Tomsod/elemental/assets/1251672/ac878043-8f6b-429b-9558-e9361e887931)

after:
![after](https://github.com/Tomsod/elemental/assets/1251672/27805676-bdf0-406b-9d09-ccd213adb884)

**Comment by aniserg** [comment]
For character with 14 base luck it gave proper 76 up to 90 base luck.

**Comment by Tomsod** [comment]
The problem here is that your base luck was 263.  That shouldn't even happen since primary stats are capped at 255; what happened here is that potion raised luck from 263 to 300-something, then checked the cap and lowered it to 255.  How did you get it this high in the first place?

**Comment by Tomsod** [comment]
Aha, apparently genie lamps can get stats above 255.  Was that it?  Good thing I'm redoing them soon.

**Comment by Tomsod** [comment]
Well, it wasn't very "soon", but the new genie lamps do respect stat limit, so that's fixed.
